### ISSUE TITLE
Unable to view image users have posted on their profile page

### ISSUE THREAD

**Issue by lindseyleggio** [lindseybosch/cats_of_disney#1]
What User Story (or feature) are you working on?

As a user, I want to be able to go into my profile and see the images I have posted.

What error am I getting? 
NoMethodError in Profiles#index
Showing /Users/lindseybosch/code/wdi/cats_of_disney/app/views/profiles/index.html.erb where line #5 raised:
undefined method `image' for #User:0x007fdd1898a358

What have I already attempted in trying to fix the error? 
- I looked up ruby document on updating users profile https://www.railstutorial.org/book/updating_and_deleting_users
- I tried to compare my code to other students code with similar models
- I tried comparing to mumbler app example on Phils github account

**Comment by tambling** [comment]
Is this still an issue? It doesn't look like you have an `image` column in `users`, so your `User model wouldn't be able to reference it (because it doesn't exist).

**Comment by lindseyleggio** [comment]
Yes it is , and I believe I do have a image model which is referenced to the user.

**Comment by tambling** [comment]
Hm. Can you post your `user.rb` file?

**Comment by lindseyleggio** [comment]
Do I need to also reference images in my User model?

**Comment by tambling** [comment]
Yeah– in `user.rb`:

```
has_one :image
```

**Comment by lindseyleggio** [comment]
class User < ActiveRecord::Base

   has_secure_password

  validates :email, presence: true, uniqueness: true
end

**Comment by tambling** [comment]
:+1:

**Comment by tambling** [comment]
Is this still a problem? If not, please close.

**Comment by lindseyleggio** [comment]
Dean helped me fix this issue. Thanks !
