### ISSUE TITLE
Upload Image from computer on to show page

### ISSUE THREAD

**Issue by lindseyleggio** [lindseybosch/cats_of_disney#2]
What User Story (or feature) are you working on?

As a user, I want my image to be stored on amazon using paperclip.

What error are you getting?

I am able to upload a image and see it on my index image page but when I go in to the image show page which is my user profile page the image is not showing up there. I can see the post has been made because it shows the image description. 

How have you attempted to fix your error?

I have been working with Jason trying to set up my paperclip gem. I also did a tutorial video https://www.youtube.com/watch?v=zeCp6IzOrpk

**Comment by tambling** [comment]
I assume you've added code since 17 hours ago? Commit and push and I'll have a look.

**Comment by lindseyleggio** [comment]
I just git pushed

**Comment by tambling** [comment]
So, are you going to `/images/:id`, or `/users/:id`? If it's the latter, you don't have anything in your `users#show` method– you need to at least do `@user = User.find(params[:id]`.

**Comment by lindseyleggio** [comment]
I should be going to my users/:id not my /images/:id so I should move my <%= image_tag @image.image_img.url(:image_show) %> code to my users show.html.erb page correct?  I just tried that and I get the error no Method error in users#show. I do have a show method in my users controller.

**Comment by lindseyleggio** [comment]
Should I change my image.rb model page, to say user_show instead of the image_show it has right now on line 8?

**Comment by lindseyleggio** [comment]
and if the answer is yes, do I then need to remigrate?

**Comment by lindseyleggio** [comment]
I also need help setting up my amazon web service - security credential - I worked with Jason on this and also did a tutorial and could figure out the last couple steps

**Comment by tambling** [comment]
Yeah. So it's giving you a `NoMethodError` _in_ `UsersController`. I would guess because you're not assigning `@image` to anything, so it's trying to call something on `nil`. If you want to go to `users/:id`, that code lives in `users#show`, and will be rendered out in `views/users/show.html.erb`, so everything in that pipeline needs to be correct.

**Comment by tambling** [comment]
And one thing at a time– get your images working first, then worry about uploading them to S3.

**Comment by lindseyleggio** [comment]
Currently my users_controller page only has 
def show 
end 

no information inside of that method, should I add something along these lines 
@image = Image.find(params[:id])

but can I use the variable @image inside my users_controller page ?

**Comment by tambling** [comment]
When you say `@image = ...`, you're not using it, you're assigning it– you can use `Image` anywhere (as a model, it's included everywhere). However, if you're in your `UsersController`, you should really be acting on your `User` model– when you go to `users/1`, you're expecting to find the `User` with the ID of 1, not the `Image` with that ID.

**Comment by lindseyleggio** [comment]
I changed it to  @user = User.find(params[:id])
get a error of NoMethodError in Users#show 

for this line

 <%= image_tag @image.image_img.url(:image_show) %>

**Comment by tambling** [comment]
Right– you never set `@image`. Instead, you should do something like `@user.images.each do |image|`.

**Comment by lindseyleggio** [comment]
I am getting a NoMethodError in Users#show 
for line 
 <%= image_tag @image.image_img.url(:image_show) %>

also I already had something along those lines in my users show.html.erb page 
where I said     <% current_user.images.reverse.each do |post| %>

is that something I should have in my controller method for show instead of the html page for show ?

**Comment by tambling** [comment]
Show me where in `users#show` you set `@image`.

**Comment by lindseyleggio** [comment]
<img width="669" alt="screen shot 2015-11-04 at 12 22 43 pm" src="https://cloud.githubusercontent.com/assets/14284642/10950843/cd8bbb1a-82ee-11e5-80fa-a4386f360a4d.png">

**Comment by lindseyleggio** [comment]
Line 22

**Comment by tambling** [comment]
I meant show me where you write `@image =`. `@image` isn't some magical thing– it's a variable, and it needs to be set. I can't make heads or tails of what you're trying to do on line 24.

**Comment by ghost** [comment]
Line 22 should read:

```
<% current_user.images.reverse.each do |image| %>
```

… and you should use the local variable `image`, not `@image`.

You are iterating over images, not posts. So your logic in there is mixed up.

**Comment by lindseybosch** [comment]
I am as confused about this as you are Dean. Which is why I am reaching out for help. I really wish I could explain in a clear way what I am line 24 is all about. I got that line from Jason which worked with Phil. I will try to watch another tutorial on the this material and get back to you with a clearer understanding.
