### ISSUE TITLE
Images not showing in Heroku link for my app 

### ISSUE THREAD

**Issue by lindseyleggio** [lindseybosch/cats_of_disney#3]
What User Story (or feature) are you working on?
As a user, I want to be able to see the images I post on the app 

What error are you getting?
My uploaded images do not show on Heroku 

How have you attempted to fix your error?
I tried doing the amazon thing to store my image database in there but have not been successful.

**Comment by tambling** [comment]
Just looked in your code and didn't see `aws-sdk` in your Gemfile. Try [this article](https://devcenter.heroku.com/articles/paperclip-s3#configuration) (make sure to use `'aws-sdk', '<2.0'`– Heroku breaks with the most recent version of `aws-sdk`).

**Comment by lindseyleggio** [comment]
do I put that in my gemfile then bundle install and then git add , git commit and git push heroku origin master ?

**Comment by lindseyleggio** [comment]
Dean I am kinda nervous to add the additional things the article you gave me is asking me to do. Do you think we can talk in person once you are done?

**Comment by ghost** [comment]
@lindseybosch  once you've run through the online video tutorial, if there is a problem, re-open the issue. (cc: @tambling)

Good luck!

**Comment by ghost** [comment]
cool!

**Comment by lindseyleggio** [comment]
Hey guys ! I finished the video but I am having issues with going into my post image page. 
https://i.imgur.com/Hr6zltN.png

**Comment by ghost** [comment]
Word.
